#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

OLDIFS="$IFS"
IFS=" "
SUBCOMMAND="$1"
export NAMESPACE=${NAMESPACE:="dokku"}
APP="$NAMESPACE/$2":latest
DOCKER=$(which docker)

if [ $# -lt 1 ] && [ "$1" != "help" ]
then
  SUBCOMMAND=help
fi

case "$SUBCOMMAND" in
  docker-direct)
    [[ $# -lt 2 ]] && dokku_log_fail "Wrong number of command line arguments: $#"
    shift
    "$DOCKER" "$@"
    ;;
  dodi)
    shift
    "$0" docker-direct "$@"
    ;;
  help)
    cat && cat<<EOF
    docker-direct <cmd>, Issues Docker command "docker <cmd>"
    dodi <cmd>, Alias for docker-direct.
EOF
    ;;
  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;
esac

IFS="$OLDIFS"